.SUFFIXES: .obj

include ../version.mak

TARGET=win.xpl
HEADERS=$(wildcard *.h)
SOURCES=$(wildcard *.c)
OBJECTS=$(SOURCES:.c=.o)
# Unzip official SDK so repo root contains SDK/CHeaders/... (override with SDK=...).
SDK?=../SDK
# Legacy layout: ../libOpenAL32 with AL/al.h and libopenal32.a
OPENAL?=../libOpenAL32
# Bundled OpenAL Soft (this repo): headers in include/, import lib in libs/Win64/
OPENAL_BUNDLE?=../openal-soft-1.25.1-bin
PLUGDIR=/e/X-Plane-12/Resources/plugins/AutoGate

CC=x86_64-w64-mingw32-gcc
LD=x86_64-w64-mingw32-gcc

override CFLAGS+=-mdll -g0 -O2 -s -Wall -fdiagnostics-color -Wno-format-overflow -DWINDOWS -DWIN32 \
	-I$(SDK)/CHeaders/XPLM -I$(SDK)/CHeaders/Widgets -DIBM=1 -DVERSION=\"$(VERSION)\"

LDFLAGS=-shared -static-libgcc -static -lpthread
LIBS= -L$(SDK)/Libraries/Win -lXPLM_64

# OpenAL: prefer bundled openal-soft; else ../libOpenAl32; else NO_OPENAL unless forced.
ifneq ($(strip $(NO_OPENAL)),1)
ifneq ($(and $(wildcard $(OPENAL_BUNDLE)/include/AL/al.h),$(wildcard $(OPENAL_BUNDLE)/libs/Win64/libOpenAL32.dll.a)),)
override CFLAGS+= -I$(OPENAL_BUNDLE)/include
LIBS+= -L$(OPENAL_BUNDLE)/libs/Win64 -lOpenAL32
else
ifneq ($(and $(wildcard $(OPENAL)/AL/al.h),$(wildcard $(OPENAL)/libopenal32.a)),)
override CFLAGS+= -I$(OPENAL)
LIBS+= -L$(OPENAL) -lopenal32
else
override CFLAGS+= -DNO_OPENAL
endif
endif
else
override CFLAGS+= -DNO_OPENAL
endif


all: $(TARGET)

.c.obj:
	$(CC) $(CFLAGS) -c $<
	
$(TARGET): $(OBJECTS)
	$(LD) -o $(TARGET) $(LDFLAGS) $(OBJECTS) $(LIBS)

clean:
	-del /q $(OBJECTS) $(TARGET) 2>NUL || exit 0

# install the just compiled target
install: $(TARGET)
	mkdir -p "$(PLUGDIR)/64"
	cp -p $(TARGET) "$(PLUGDIR)/64/."

# create the whole plugin directory
plugin: $(TARGET)
	mkdir -p "$(PLUGDIR)/64"
	cp -p $(TARGET) "$(PLUGDIR)/64/."
