.SUFFIXES: .obj

include ../version.mak

TARGET=win.xpl
HEADERS=$(wildcard *.h)
SOURCES=$(wildcard *.c)
OBJECTS=$(SOURCES:.c=.o)
# Unzip official SDK so repo root contains SDK/CHeaders/... (override with SDK=...).
SDK?=../SDK
PLUGDIR=/e/X-Plane-12/Resources/plugins/AutoGate

CC=x86_64-w64-mingw32-gcc
LD=x86_64-w64-mingw32-gcc

override CFLAGS+=-mdll -g0 -O2 -s -Wall -fdiagnostics-color -Wno-format-overflow -DWINDOWS -DWIN32 \
	-I$(SDK)/CHeaders/XPLM -I$(SDK)/CHeaders/Widgets -DIBM=1 -DVERSION=\"$(VERSION)\"

LDFLAGS=-shared -static-libgcc -static -lpthread
LIBS= -L$(SDK)/Libraries/Win -lXPLM_64

# OpenAL: prefer bundled openal-soft (../openal-soft-1.25.1-bin); else legacy ../libOpenAL32.
OPENAL_SOFT?=../openal-soft-1.25.1-bin
OPENAL_LEGACY?=../libOpenAL32

OPENAL_HEADER:=$(wildcard $(OPENAL_SOFT)/include/AL/al.h)
OPENAL_IMPORT:=$(wildcard $(OPENAL_SOFT)/libs/Win64/libOpenAL32.dll.a)
ifneq ($(strip $(OPENAL_HEADER)),)
ifneq ($(strip $(OPENAL_IMPORT)),)
override CFLAGS+= -I$(OPENAL_SOFT)/include
LIBS+= -L$(OPENAL_SOFT)/libs/Win64 -lopenal32
else
override CFLAGS+= -DNO_OPENAL
endif
else
OPENAL_HEADER:=$(wildcard $(OPENAL_LEGACY)/AL/al.h)
OPENAL_IMPORT:=$(wildcard $(OPENAL_LEGACY)/libopenal32.a)
ifneq ($(strip $(OPENAL_HEADER)),)
ifneq ($(strip $(OPENAL_IMPORT)),)
override CFLAGS+= -I$(OPENAL_LEGACY)
LIBS+= -L$(OPENAL_LEGACY) -lopenal32
else
override CFLAGS+= -DNO_OPENAL
endif
else
override CFLAGS+= -DNO_OPENAL
endif
endif


all: $(TARGET)

.c.obj:
	$(CC) $(CFLAGS) -c $<
	
$(TARGET): $(OBJECTS)
	$(LD) -o $(TARGET) $(LDFLAGS) $(OBJECTS) $(LIBS)

clean:
	-del /q $(OBJECTS) $(TARGET) 2>NUL || exit 0

# install the just compiled target
install: $(TARGET)
	mkdir -p "$(PLUGDIR)/64"
	cp -p $(TARGET) "$(PLUGDIR)/64/."

# create the whole plugin directory
plugin: $(TARGET)
	mkdir -p "$(PLUGDIR)/64"
	cp -p $(TARGET) "$(PLUGDIR)/64/."
