.SUFFIXES: .obj

include ..\version.mak

TARGET=win.xpl
HEADERS=$(wildcard *.h)
SOURCES=$(wildcard *.c)
OBJECTS=$(SOURCES:.c=.o)
SDK=../../../SDK/SDK
OPENAL=../../../libOpenAL32
PLUGDIR=/e/X-Plane-12/Resources/plugins/AutoGate

CC=x86_64-w64-mingw32-gcc
LD=x86_64-w64-mingw32-gcc

override CFLAGS+=-mdll -g0 -O2 -s -Wall -fdiagnostics-color -Wno-format-overflow -DWINDOWS -DWIN32 \
	-I$(SDK)/CHeaders/XPLM -I$(SDK)/CHeaders/Widgets -DIBM=1 -DVERSION=\"$(VERSION)\"

LDFLAGS=-shared -static-libgcc -static -lpthread
LIBS= -L$(SDK)/Libraries/Win -lXPLM_64

# Optional OpenAL support: compile without audio when OpenAL dev files are missing.
OPENAL_HEADER:=$(wildcard $(OPENAL)/AL/al.h)
OPENAL_IMPORT:=$(wildcard $(OPENAL)/libopenal32.a)

ifneq ($(strip $(OPENAL_HEADER)),)
ifneq ($(strip $(OPENAL_IMPORT)),)
override CFLAGS+= -I$(OPENAL)
LIBS+= -L$(OPENAL) -lopenal32
else
override CFLAGS+= -DNO_OPENAL
endif
else
override CFLAGS+= -DNO_OPENAL
endif


all: $(TARGET)

.c.obj:
	$(CC) $(CFLAGS) -c $<
	
$(TARGET): $(OBJECTS)
	$(LD) -o $(TARGET) $(LDFLAGS) $(OBJECTS) $(LIBS)

clean:
	-del /q $(OBJECTS) $(TARGET) 2>NUL || exit 0

# install the just compiled target
install: $(TARGET)
	mkdir -p "$(PLUGDIR)/64"
	cp -p $(TARGET) "$(PLUGDIR)/64/."

# create the whole plugin directory
plugin: $(TARGET)
	mkdir -p "$(PLUGDIR)/64"
	cp -p $(TARGET) "$(PLUGDIR)/64/."
